from datetime import datetime
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

class UretimEmri(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    musteri_adi = db.Column(db.String(200), nullable=False)
    urun_adi = db.Column(db.String(200))
    usiparis_miktari = db.Column(db.String(50))
    tabaka_adedi = db.Column(db.String(50))
    kagit_cinsi = db.Column(db.String(100))
    gramaj = db.Column(db.String(50))
    kagit_olcusu_1 = db.Column(db.String(50))
    kagit_olcusu_2 = db.Column(db.String(50))
    bicak_kodu = db.Column(db.String(100))
    bicak_olcusu_1 = db.Column(db.String(50))
    bicak_olcusu_2 = db.Column(db.String(50))
    renk_sayisi = db.Column(db.String(50))
    renk_bilgisi = db.Column(db.String(100))
    verim = db.Column(db.String(50))
    selefon_1 = db.Column(db.String(50))
    selefon_2 = db.Column(db.String(50))
    varak_yaldiz = db.Column(db.String(50))
    gofre = db.Column(db.String(50))
    yapistirma = db.Column(db.String(50))
    paketleme = db.Column(db.String(100))
    siparis_durumu = db.Column(db.String(50))
    notlar = db.Column(db.Text)
    baski_adedi = db.Column(db.String(50))
    selefon_adedi = db.Column(db.String(50))
    kesim_adedi = db.Column(db.String(50))
    karton_agirligi = db.Column(db.String(50))
    tarih = db.Column(db.String(50))
    olusturma_tarihi = db.Column(db.DateTime, default=datetime.now)